- name: Add conf for containerd
  become: yes
  blockinfile:
    create: yes
    group: "{{ k8s_group }}"
    path: "/etc/modules-load.d/containerd.conf"
    block: |
          overlay
          br_netfilter

- name: modprobe
  become: yes
  shell: |
          modprobe overlay
          modprobe br_netfilter

- name: Add conf for containerd
  become: yes
  blockinfile:
    create: yes
    group: "{{ k8s_group }}"
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    block: |
           net.bridge.bridge-nf-call-iptables = 1
           net.ipv4.ip_forward = 1
           net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply new settings
  command: sudo sysctl --system

- name: install containerd
  shell: |
          sudo apt-get update && sudo apt-get install -y containerd
          sudo mkdir -p /etc/containerd
          sudo containerd config default | sudo tee /etc/containerd/config.toml
          sudo systemctl restart containerd